### ISSUE TITLE
OSMCha (changeset) for US RR Tunnel Project - documentation from Leslie

### ISSUE THREAD

**Issue by GDMatthews** [publicdomainmap/issues#10]
Hello US RR Tunnel Team,

Here is some basic information on OSMCha (changeset) from the Instructions.  If you want a full copy, let me know.

Part V – View Collected Changesets

1.	From the Manage and Projects tabs, open the project.  At the bottom of the page are the green More statistics button and the white Changesets in OSMCha button.  

 
2.	Open the Changesets in OSMCha to view your updates.  Select one of the Changesets on the left and the map will appear with the new feature.  Click on the new feature in the map to view the details.  Click the History tab and select either OSM or Deep History.  The Deep History record information contains historical activity and saved attributes, which can validate our records.
 

3.	Select the History tab to see a history of the attributes on the OSM Deep History page.  Jennings Anderson created Deep History.  His website is https://jenningsanderson.com but it’s inaccessible from DOT computers.
4.	OSM records are stored at https://github.com/osmlab/osm-deep-history  (e.g. use 17054656 as the Way for Moffat Tunnel).

**Comment by GDMatthews** [comment]
This is primarily for documentation. If necessary, please keep for reference somewhere on Git Hub. Greg

**Comment by jessbeutler** [comment]
This information can be found within the document [here](https://github.com/publicdomainmap/Files/blob/Documentation-for-tm.publicdomainmap.org/20210907%20Instructions%20for%20US%20RR%20Tunnel%20Project.docx).
