### ISSUE TITLE
Instructions for US RR Tunnel Project on Tasks.TeachOSM.org - Documentation from Leslie

### ISSUE THREAD

**Issue by GDMatthews** [publicdomainmap/issues#11]
Hello Tunnel’s Team,

Attached is the updated Instructions for US RR Tunnel Project.  I added in a new Part VII – Validate a Completed Task.  It has the basics that we discussed at the last meeting, but needs to be fleshed out a bit more, i.e. what does the validator validate – the segment position, the labeling, the tunnel designation, etc?

I also updated the Detailed Instructions under Part III – TM Project Creation starting on page 6.  I revised it to talk about selecting a Segment of the railroad.  I recommend adding in more detail.  Project 65/Area 61 also has the Detailed Instructions revised, but I’ve no time to revise the other projects.  This is one of the more interesting areas with many Moffat tunnels. 

I’ve enjoyed working with all of you!  Good luck with this project and with your other endeavors.
- Leslie Haig

**Comment by GDMatthews** [comment]
Please find the related email originally sent from Leslie or re-forwarded from Greg. Document somewhere within Jira so we have as a reference.

**Comment by mayashap** [comment]
I moved the full documentation into the "files" --> https://github.com/publicdomainmap/Files/tree/Documentation-for-tm.publicdomainmap.org
