### ISSUE TITLE
# 16 Colorado RR Tunnels - issue with "projects to map" vs "projects to validate" 

### ISSUE THREAD

**Issue by GDMatthews** [publicdomainmap/issues#12]
Project `#16` has been mapped by Greg Matthews but is still showing up as a "project to map". It should only show up in the "projects to validate" category. See Greg for details.

**Comment by mayashap** [comment]
Maya and Greg looked into this. the task turns blue for "ready for validation" however the project stay under "ready for mapping" filter. when changing the filter to "ready for validation" no project sows up.

**Comment by jessbeutler** [comment]
Confirming that this does not appear to be an issue with other completed tasks. Only TM Project `#16` for now. Tagging this as a bug, as opposed to a consistent issue across projects.

**Comment by jessbeutler** [comment]
Fixed.
