### ISSUE TITLE
Remove references to CO RR project in the original Teach OSM

### ISSUE THREAD

**Issue by GDMatthews** [publicdomainmap/issues#14]
https://tasks.teachosm.org/explore?osm_oauth_token=Z8bqf7cwk2D4TrnQVTqvtrJlT2hupkKyD8VoL1L7&osm_oauth_token_secret=zElDS1fw0JRF744LNhAYU8ZJqEDaFEFmFsHaBvkn&picture=https%3A%2F%2Fwww.openstreetmap.org%2Frails%2Factive_storage%2Frepresentations%2Fredirect%2FeyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1VkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--99e3c663aa855d6a938092f6b7ad97b8b396823e%2FeyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVdscGFRPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ%3D%3D--eebe711a4715314afd416ccd673530bbf8ac1b24%2FPA310326.jpg&redirect_to=%2Fexplore&session_token=MjU4MTIy.YU4N3g.tQP-KIFm_zv0MOanZQdXHt91-s8&text=colorado&username=GMatt

Not sure if this link will work but you can look in Teach OSM, search for Colorado and find two of our old project in there that should be removed. 

Greg

**Comment by jessbeutler** [comment]
All USDOT projects have been archived in the TeachOSM Tasking Manager.
