### ISSUE TITLE
Need to have either one state per project or no more than 2 or 3 states per project if we expand nationally

### ISSUE THREAD

**Issue by GDMatthews** [publicdomainmap/issues#15]
Just noting that we could have thousands of projects once we expand this project nationally. We really need 1 project per state for future project.

**Comment by jessbeutler** [comment]
Best practices/limitations on number of open projects should be part of standard PM guidance. I've opened a new issue for adding this to documentation in issue #20 

To clean up our own pilot tasks, I have (loosely) followed the guidance in #20 by reducing Colorado RR active projects to 3 active mapping, and 3 active validation.

**Comment by quincylvania** [comment]
This limit has been lifted. We can now have a full state in one project.
