### ISSUE TITLE
Update meeting minutes

### ISSUE THREAD

**Issue by mayashap** [publicdomainmap/issues#18]
Please update minutes here https://github.com/publicdomainmap/Files/blob/main/Meeting_Minutes.md
including the date of each meeting

**Comment by GDMatthews** [comment]
I've added my notes (OpenStreetMap Notes2) to the files directory. I also added old meeting notes as copy/paste to the current notes file. I believe my related tasks are now complete - Greg

**Comment by jessbeutler** [comment]
**10/5 Meeting**
- Notes added to GitHub [here](https://github.com/publicdomainmap/Files/blob/main/Meeting_Minutes.md). 
- Live notes can also be found on [HackMD](https://hackmd.io/@PlbLGKjlQ_-LtKPDiuyMKg/SJvpOzc4K)
