### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by jessbeutler** [publicdomainmap/issues#19]
SSL Certificate expired as of 9/30/21, this needs to be renewed.

**Comment by jimmyrocks** [comment]
Oops, this should be on a schedule! But the scheduled task didn't have the right permissions. It's ready to go now!

**Comment by jessbeutler** [comment]
SSL Certificate has expired again for publicdomainmap.org

**Comment by quincylvania** [comment]
Re-renewed
