### ISSUE TITLE
Add USGS imagery, and remove unneeded imagery from imagery.json Shapefile

### ISSUE THREAD

**Issue by jimmyrocks** [publicdomainmap/issues#2]

**Comment by tsatjj** [comment]
I created a json file for USGS Imagery. I did a default bounding box for testing purposes only, we can modify as required. Only "tag" I am not sure about is the "template" tag, but I figure we could test and see how it goes. 
[https://github.com/tsatjj/editor/blob/develop/data/USGSimagery.json](url) (I couldn't get to open by clicking on link or right-click - copy link, but highlight then copy-paste worked)
Check out the file and let me know what you think.

**Comment by GDMatthews** [comment]
Waiting on Jim to implement this.

**Comment by jessbeutler** [comment]
Reviewed in group meeting
