### ISSUE TITLE
Address server needs

### ISSUE THREAD

**Issue by jessbeutler** [publicdomainmap/issues#27]
University of Arizona may have space. We will need to tell them hardware specs for what we need to run the server and how much storage we need.

**Comment by jessbeutler** [comment]
From UA:
- They own a server in CyVerse that has 100TB of space on it which was established for geospatial archiving of data, I would be okay putting OSM data on there, but I’m not sure how big your archive is now
-  They can probably get some VMs out of the CyVerse pool that we could use to set up a service on. If we give them a set of deployment instructions, they could probably get a VM stood up for your team to test out

From Jimmy:
- Current specs: Ubuntu, 2 CPUs, 4GB ram, 50GB disk space
- ~Ideal specs: 4cpu, 4GB ram, 75gb disk~ 4cpu, 4gb, 150GB

**Comment by jessbeutler** [comment]
@mcawley What are the next steps here?

**Comment by jessbeutler** [comment]
Test Deployment being set up on Cyverse. Conversation between Jim, Martijn, Jess, Maggie, & Tyson on OSM US slack. Current steps:

- [ ] Confirm Tyson's repo access needs
- [ ] Provide Tyson with deployment instructions
- [ ] Jim, Martijn, & Jess to set up accounts on cyverse

**Comment by quincylvania** [comment]
Server access is all set.
