### ISSUE TITLE
Find FRA data that shows railroad tunnel center points. 

### ISSUE THREAD

**Issue by GDMatthews** [publicdomainmap/issues#6]
Find FRA data that shows railroad tunnel center points. This is the data that was hosted by HIFLD. Provide file to Jim so he can add as a reference with our iD application.

**Comment by mayashap** [comment]
e mailed Raquel and Derald about this.

**Comment by jessbeutler** [comment]
Files shared by Raquel and uploaded to Files [here](https://github.com/publicdomainmap/Files/blob/main/RailroadTunnels.gdb.zip)
